---
title: "MultipredictorInter.Rmd"
author: "F.A. Barrios"
date: "<small>`r Sys.Date()`</small>"
output:
  output:
  rmdformats::readthedown:
    highlight: kate
  pdf_document: default
description: "to prepare homeworks"
---

```{r setup, echo=FALSE, cache=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

```{r message = FALSE}
# Multilevel categorical predictors Chap 4 Vittinghoff
# libraries
#
library(tidyverse)
library(emmeans)
library(multcomp)
library(MASS)
library(car)
#
setwd("~/Dropbox/GitHub/Class2020")
# loading the HERS data set from Vittinghoff's data
hers <- read_csv("DataRegressBook/Chap3/hersdata.csv")
```

# Interaction

```{r}
# Now for the group with Hormone Therapy the complete HERS cohort
# Model of cholesterol LDL and the effect of Hormone Therapy (HT) and
# Statin use model is at the one year visit (to se the HT effect)

hers <- mutate(hers, HT = factor(HT))
hers <- hers %>% mutate(HT = relevel(HT, ref = "placebo"))

# For the first year visit LDL levels at one year LDL1
LDL1_model <- lm(LDL1 ~ HT * statins, data = hers)
S(LDL1_model)

# For the table 4.15 of the book, to test for the linear 
# combination of the coefficients for the interaction to
# TEST the linear combination of the coefficients for HT
# and the statin interaction b1 and b3 the third part of table 4.15

coefeq <- matrix(data=0, nrow = 1, ncol = length(LDL1_model$coefficients))
colnames(coefeq) <- names(LDL1_model$coefficients)
coefeq
coefeq[1, "HThormone therapy"] <- 1
coefeq[1, "HThormone therapy:statinsyes"] <- 1
coefeq %*% LDL1_model$coefficients

# coeftest <- glht(model= LDL_model, linfct= coefeq, rhs= 0, alternative= "greater")
coeftest <- glht(model= LDL1_model, linfct= coefeq, rhs= 0)
summary(coeftest)

# Example of LDL after one year of HT and physact
# This is the table 4.16 of the book, effect of the hormone therapy
# combined with effects of physical activity at the one year visit
# now to estimate the linear combination of the coefficients
hers <- mutate(hers, physact = factor(physact, levels=c("much less active","somewhat less active","about as active","somewhat more active","much more active")))
LDL1phys_model <- lm(LDL1 ~ HT * physact, data = hers)
S(LDL1phys_model)

# The coefficients test for interaction
# can be done with glht()

coef_LDL1phys <- matrix(data=0, nrow = 1, ncol = length(LDL1phys_model$coefficients))
colnames(coef_LDL1phys) <- names(LDL1phys_model$coefficients)

# E[LDL|x] = b0 + b1 HT + b2 physact + b3 HT:physact
# we will look at slope = b3 BMIc; coeff = 0, 0, 0, 0, 0, 1, 1, 1, 1
# to test of significance

coef_LDL1phys[1, "HThormone therapy:physactsomewhat less active"] <- 1
coef_LDL1phys[1, "HThormone therapy:physactabout as active"] <- 1
coef_LDL1phys[1, "HThormone therapy:physactsomewhat more active"] <- 1
coef_LDL1phys[1, "HThormone therapy:physactmuch more active"] <- 1
coef_LDL1phys %*% LDL1phys_model$coefficients
coef_LDL1phys
coef_LDL1phystest <- glht(model= LDL1phys_model, linfct= coef_LDL1phys, rhs= 0)
S(coef_LDL1phystest)

# Example of BMI and statins, with interaction
# Model of LDL and BMI*statins and other variables
hers <- mutate(hers, statins = factor(statins))
hers <- mutate(hers, nonwhite = factor(nonwhite))
hers <- mutate(hers, smoking = factor(smoking))
hers <- mutate(hers, drinkany = factor(drinkany))
hers <- mutate(hers, BMIc = BMI - mean(BMI, na.rm=TRUE))
LDLbmi_model <- lm(LDL ~ statins*BMIc + age + nonwhite + smoking + drinkany, data = hers)
summary(LDLbmi_model)

# For the table 4.17 of the book, to test for the linear 
# combination of the coefficients for the interaction to
# TEST the linear combination of the coefficients for HT

coef_LDLbmi <- matrix(data=0, nrow = 1, ncol = length(LDLbmi_model$coefficients))
colnames(coef_LDLbmi) <- names(LDLbmi_model$coefficients)

# E[LDL|x] = b0 + b1 statins + b2 BMIc + b3 statins:BMIc + b4 age
#           + b5 nonwhite + b6 smoking + b7 + drinkany
# we will look at slope = b2 + b3 BMIc; coeff = 0, 0, 1, 1, 0, 0, 0, 0

coef_LDLbmi[1, "statinsyes"] <- 0
coef_LDLbmi[1, "BMIc"] <- 1
coef_LDLbmi[1, "statinsyes:BMIc"] <- 1
coef_LDLbmi %*% LDLbmi_model$coefficients
coef_LDLbmi
coef_LDLbmitest <- glht(model= LDLbmi_model, linfct= coef_LDLbmi, rhs= 0)
summary(coef_LDLbmitest)

# Comp of regular linear model and robust and some standard error handling
#
glucose_model <- lm(glucose ~ diabetes + BMI + age + drinkany, data= hers)
summary(glucose_model)

# MASS rlm()
glucose_rmodel <- rlm(glucose ~ diabetes + BMI + age + drinkany, data= hers)
summary(glucose_rmodel)
#
glucose_rmodel_bi <- rlm(glucose ~ diabetes + BMI + age + drinkany, psi= psi.bisquare, data= hers)
S(glucose_rmodel_bi)
#
```